### ISSUE TITLE
App in F-Droid is different

### ISSUE THREAD

**Issue by agilob** [wish7code/openbmap#101]
Not sure where the problem is, but the application in F-Droid repo is different than when self-build. My build looks more modern, like android 4 supposed to look like, it doesn't crash on android 4.1.2 when switching tabs. Graphs is more verbose. Also icon if different. Could you increase version to update fdroid app?

**Comment by sim6** [comment]
Yes, please, release a new version. Thanks!

**Comment by wish7code** [comment]
Your voice has been heard: I just forgot to include the version tag in my latest push, so F-Droid didn't see the new version :D

New version should appear in F-Droid probably tomorrow or the day after..

**Comment by agilob** [comment]
Thanks

**Comment by agilob** [comment]
There was no update :<

**Comment by wish7code** [comment]
We got a build issue, see https://f-droid.org/wiki/page/org.openbmap/lastbuild_17
Working on it..

**Comment by wish7code** [comment]
Another try: pushed 447d6cf7d5 to the repositories

**Comment by wish7code** [comment]
Update: F-Droid now reports successful build, so they should roll it out very soon too.
see https://f-droid.org/wiki/page/org.openbmap/lastbuild_19

**Comment by agilob** [comment]
Thank you!

**Comment by sim6** [comment]
Thanks!

**Comment by michitux** [comment]
The new version still hasn't been published on F-Droid, the [wiki page]( https://f-droid.org/wiki/page/org.openbmap) still says that the build has been disabled because java compilation fails.

**Comment by gdt** [comment]
It seems that the failing build of 18 is *after* the successful build of 19.
FWIW, I have 0.8.11 installed, with 0.8.8 the most recent available. While I have managed to build myself, I never pushed the apk, so my 0.8.11 came from f-droid at some point.

I suggest a 0.8.12 to let f-droid start building again, and for good measure.

**Comment by agilob** [comment]
Hi @wish7code could you make a new release for fdroid please?

**Comment by amilopowers** [comment]
I would love to see that as well.

**Comment by AreYouLoco** [comment]
Mee too.


-------- Original Message --------
