### ISSUE TITLE
gradle build fails due to lint warnings

### ISSUE THREAD

**Issue by gdt** [wish7code/openbmap#107]
I'm trying to build from up-to-date git, using gradle 2.9.   I get an error that lint found 200 issues.  If I do "gradle -x lint build", then the build succeeds.   I have the impression that the gradle  config should handle this, but I'm new to gradle.

Perhaps I should be using Android Studio vs gradle on the command line; a README that gives brief instructions would be really helpful.

**Comment by gdt** [comment]
In Android Studio, I imported a gradle project, and then I was able to get an APK.   I had expected gradle from the command line to work.  Perhaps this is obvious, but a "To build radiocells, you must use Android Studio" would help.

It also seems odd that the Android Studio build doesn't fail due to lint warnings.

**Comment by wish7code** [comment]
Hey Greg,

at first I really, really want to apologize for not having replied on any of your previous highly valuable  suggestions before! In particular your idea of 2G, 3G and LTE clustering, which is by now implemented server side, brought a major improvement on data quality. So a huge thanks for all of that!!!

I hope the upcoming year will be much less busy than this year, so step by step we could solve all the other points you brought up.

Following your advice I added a short notice in the readme @ https://github.com/wish7code/openbmap/blob/master/README.md

Please let me know, when you need any additional information!

Cheers 
Toby

PS: in case of specific questions to the code we could also continue our discussion in private email (team@radioc......org)

**Comment by gdt** [comment]
Thanks; the new README would have been enough to get me going faster.
