### ISSUE TITLE
Translation proposition. Locales support.

### ISSUE THREAD

**Issue by AreYouLoco** [wish7code/openbmap#111]
I would like to make a translation of RadioBeacon to polish.

Is is possible for the client to support local languages? Is it hard to implement?

**Comment by wish7code** [comment]
Sounds great!! Actually it should be very easy to implement..

Let's continue our discussion next week when I'm back home.. The network connection here on the road is way too bad :-(

On January 12, 2016 12:47:08 AM GMT+08:00, AreYouLoco? <notifications@github.com> wrote:
>I would like to make a translation of RadioBeacon to polish
>
>Is is possible for the client to support local languages? Is it hard to
>implement?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/wish7code/openbmap/issues/111

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by AreYouLoco** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

No problem. Maybe I can ask some friends to help me and I can try Dutch as well.

And there slowly we are getting somewhere.
Thank for all the effort so far with the project.

In touch then.

-----BEGIN PGP SIGNATURE-----

iQJEBAEBCgAuJxxBcmVZb3VMb2NvPyA8YXJleW91bG9jb0BwYXJhbm9pY2kub3Jn
PgUCVpTo4AAKCRD9y75DgGLNL+E3D/9684FEwIoKugBXAf3kmwNXnJFxD48Kt2mF
qdjBSQXEAz/58V47poJ1ncDp5/dm3dWbKwF/LWgaEFenBZmH5n2t08prqWEeFg7f
JIGurFAS3BsbAX6F8HlnvaOjcHNmbUMRehPdr6w+mNB0NYdveVJcxzMr1CVvdoJ0
OqO9iqecPEkpqrqgYx0M7LpxVeBRShdd3e4MV9lTgvkIk8oHhUoiltsIhfRbVT2u
bU4c2ja74GVcqvXovLZEOb3FB2PCc7WD64GVuCISO5IDCqawnLHSx0vX3apxXlbZ
JPRYpD9NiolOtInWzyZfEVVqLsHidPDr9v5oq7HClzw28fxG6oYUVn4AUMPVE504
rOSzXYnD2q/39HnkcifvphzlGB6Z2DtYBcp+hEb2RNg5NGd9P8Rf5wgQJEyEDiUV
XcVxjKVfE6xkRQNXTc19ZqkAyhFi8CS2lKe3wTLBqmOXdMn/lZDTTtrS51a5VbRE
sW0QqNYBG0kGobZjKgo6IKgkv5e4TAkxRFxDDvHPTajmfd7tXJQF9BzP4bdGEbWd
zqaVz5iQ3GjCrIw7CetFR+UNFKQk9U23hzUO1QFmt7EM3dAX4X+UVaK/NRTxYJ1C
q050CRIhEqqDHgY8bj+GmFDiTm/VayndNomfRT9PLGjKYh415D6sC9EPzYaia/2P
wZTio3IAqg==
=G16U
-----END PGP SIGNATURE-----

**Comment by wish7code** [comment]
Applied for an free open source hosting account at weblate..
Interface looks pretty cool and easy to use (e.g. https://hosted.weblate.org/projects/osmand/main/).

Let's wait for their response...

**Comment by AreYouLoco** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Ok thx. I wait for message and i will translate later on..

...but a'propos OSM in the future there could be possibility to navigate to nearest open wifi network if osm will use your database on their maps. Cool thing to ask tho;)

On January 22, 2016 10:18:55 PM GMT+01:00, wish7code <notifications@github.com> wrote:
>Applied for an free open source hosting account at weblate..
>Interface looks pretty cool and easy to use (e.g.
>https://hosted.weblate.org/projects/osmand/main/).
>
>Let's wait for their response...
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/wish7code/openbmap/issues/111#issuecomment-174051977
-----BEGIN PGP SIGNATURE-----

iQJEBAEBCgAuJxxBcmVZb3VMb2NvPyA8YXJleW91bG9jb0BwYXJhbm9pY2kub3Jn
PgUCVqPnZAAKCRD9y75DgGLNL3yrD/sEaqSrsN7r5NwNOsW4QsBuJqATNd05+YfQ
10O6OUkW+ZXSu2rvZupftOPR10FGYnG9yPlyhnVb3uBOaH1R2rdgYchOG+aSq5Sf
sh/NfzdOZhlSV4VtV/GOD9T7xPmX7HM0AJQ+5o5icRxZCk9qi4G5/vPA5Eb0pDJG
4wiHUnXYGQRBzyUGgKa3LyPzHaYC0sCvgqpfUoRMXbcgtKqyUnfn69U0hdH/J+GX
mQ1h4Xw4TLqJCpQbKGNDLYCVbVlmp9sJUcoXZSiMAcJmkp3avWOjouRkuxQuv9sr
b2llAGj9WYhAjgRJTQ34ktJ7aX1b2kDGdcQihYm3e34o6NEk1oQx09BROfAODzc9
qVMcCwSDZQHTXv8YOyEiGCfGZx6PXCuqEdTsUdWQiRL7gs/LxdWq8FRRNkIbcV2c
y/7Xv05+AuQwRTMcHY+s6vOF3uqnfSjhXvrCYJACZLlHXnDFQsY80fH+3qHCsY7b
DKFCDU9poQZi8nJ/00b8ZNUO9JmHKVJNC+s1jaZGcrJe1J75wuiLQcz5rhrDiASD
tTMt0Ii9UiVAmqEz7WY5/7ED1q0yvZ5f9OzMfE+pzsHJO9tSZCliv/7glIyc6HLm
HNX+tPkfHmB8avo/E1EBuMam+kNCz8SJIWAuMXYkT8OHwBPZ9eYp7FsukCJ6J1bj
TGXHM6cuJg==
=LabZ
-----END PGP SIGNATURE-----

**Comment by wish7code** [comment]
Weblate is not responding, so we got to go on our own...

I added a dummy file @ https://github.com/wish7code/openbmap/blob/master/android/app/src/main/res/values-pl/strings.xml

To translate save as text file and replace the dummies with their Polish counter-parts.
Then you may send it back to team@radio...org or file a merge request..

Looking forward to going international ;-)
Cheers
Toby

**Comment by AreYouLoco** [comment]
Cool.

I am going to translate end send merge request via github.
I think the most handy for me and for you.

When I finish with polish I am going to ask some friends help to do other languages. Dutch and Greek I think we can manage later.

So first my job with polish.

Greets

**Comment by wish7code** [comment]
No problem: added Dutch and Greek dummies with 0c4fddf6b3057ed

**Comment by AreYouLoco** [comment]
I am quite sure country code for greek is GR not EL... but its not THAT important.
I finished polish translation v1 and I send merge request.

Review, merge and enjoy

**Comment by wish7code** [comment]
> I am quite sure country code for greek is GR not EL...

Me too ;-)

Oddly Android seems to use **ISO 639-1**, i.e EL instead of the more common **ISO 3166** (GR),
see https://developer.android.com/guide/topics/resources/providing-resources.html#AlternativeResource

**Comment by wish7code** [comment]
Finally weblate granted us an free open source account @
https://hosted.weblate.org/projects/openbmap/strings/pl/

I love their simple UI interface... You can log in using your Github, Bitbucket, Google or Facebook account and translations can be pulled upstream to the repositories..
Pretty cool..

**Comment by wish7code** [comment]
Thanks for your updates! I've seen Polish translations are pretty complete!

I'd suggest we close this issue by now. For future contributors I added a short description @ https://radiocells.org/default/wiki/translate
