### ISSUE TITLE
Still invalid position when none of the wifis in range is known in openbmapnlp backend 0.1.11

### ISSUE THREAD

**Issue by jw243** [wish7code/openbmap#117]
There still seems to be a bug in version 0.1.11 of the openbmapnlp backend. When none of the wifis in range is known in offline mode, it displays the position 0.00E / 0.00N in the middle of the ocean south west of Nigeria. Instead it should rather not find a position at all.

This issue refers to issue #6 in the org.openbmap.unifiedNlpProvider repo on github. The issue could not be reproduced with version 0.1.4, hence the issue was closed, but it seems to be present again in version 0.1.11.

**Comment by wish7code** [comment]
Thanks for reporting! I cloned the issue in to the openbmapnlp issue tracker @ https://github.com/wish7code/org.openbmap.unifiedNlpProvider/issues/17
