### ISSUE TITLE
Graph on website

### ISSUE THREAD

**Issue by amilopowers** [wish7code/openbmap#131]
Please help me understand the graph here: https://www.radiocells.org/

It says that we collected "473.647k" cells. That would mean that we have 473.647.000 cells. But am I right that we have "only" 473.674 cells or not? I am very confused about that of course I hope we have 473 Million cells but I can't believe it I am sorry. Maybe this is a confusion between european an US ways of tellling numbers but "k" means the same thing as "000" in Europe. Though I don't know where you come from ;-).

Btw: Would it be useful and possible to add country specific graphs and statistics? The  cell Provider page says "Update in progress.. Please come back later" and Operator pages (like Sunrise) say: "Statistics: No records found". Ist that due to the server migration? I would love to have some details here.

**Comment by wish7code** [comment]
Radiation overkill! Thanks for reporting, fortunately just a typo on the number formatting.

I created a separate issue for country specific stats, see #132
Also will check, why we don't have cell providers statistics. Fix will follow..

**Comment by amilopowers** [comment]
Something minor: Here https://radiocells.org/stats/scoreboard we can see that we see the same amount of already known cells and new ones. That seems weird to me. Those two lines must be different like they were until 2015-06.

**Comment by mvglasow** [comment]
I notice this thing comes and goes. Here's a good one:
![openbmap-stats-ok](https://cloud.githubusercontent.com/assets/2377496/14226716/75b06f04-f8ea-11e5-8176-8035d3cd9785.png)

And here's a bad one:
![openbmap-stats-nok](https://cloud.githubusercontent.com/assets/2377496/14226721/95d5426e-f8ea-11e5-8c83-076bfa3e57b0.png)

**Comment by amilopowers** [comment]
I am also wondering if we lost users... In March we didn't find not very much cells.
