### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by amilopowers** [wish7code/openbmap#137]
Since yesterday the website (server) seems to be down. I can't reach https://radiocells.org and I can't upload scans.

**Comment by wish7code** [comment]
Hey Ulrich!
Check again, it should work since 5min ago..
Hardware replacement has been a nightmare this time..

On March 15, 2016 8:44:57 AM GMT+01:00, amilopowers <notifications@github.com> wrote:
>Since yesterday the website (server) seems to be down. I can't reach
>https://radiocells.org and I can't upload scans.
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/wish7code/openbmap/issues/137

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by amilopowers** [comment]
Nice job! Thank you!
