### ISSUE TITLE
Disappeared from user stats

### ISSUE THREAD

**Issue by mvglasow** [wish7code/openbmap#143]
I've noticed that my account seems to have disappeared from the "all time contributions" user stats. Last time I looked I had slightly above 4 million wifis. Could I have become the victim of an integer overflow?

**Comment by agilob** [comment]
Confirmed, I'm not on the list too.

**Comment by wish7code** [comment]
And the all time winner is ...  see  https://radiocells.org/stats/scoreboard

Thanks for reporting, should be fixed now..
