### ISSUE TITLE
Radiobeacon cannot upload cell data

### ISSUE THREAD

**Issue by mbethke** [wish7code/openbmap#86]
I installed Radiobeacon a few days ago and apparently it collects data just fine. After roaming the city for a while I always have a couple hundred WLANs and a few dozen cells However, only the WLANs get uploaded correctly -- you can easily see the results because I'm currently the only uploader in Laos. If I check "keep uploaded files" in the prefs, a file called `filesV2_457_log_$TIMESTAMP-cellular.xml` sticks around, looking good. xmllint has nothing to complain about it. However, apparently the server does not accept it or rather silently discards it:

    I/g       (11623): Client version is up-to-date: 00.8.00
    I/au      (11623): Good: User and password provided
    I/au      (11623): Looping over pending exports
    I/au      (11623): Will process export 11
    I/k       (11623): Exporting cells
    D/a       (11623): Start cell export. Data source:  SELECT cells._id, type,
    is_cdma, is_serving, is_neighbor, cid, actual_cid, utran_rnc, lac, mcc, mnc,
    psc, baseid, networkid, systemid, OperatorName, Operator, dbm, asu,
    cells.timestamp, request_pos_id,  "req"."latitude" AS "req_latitude",
    "req"."longitude" AS "req_longitude", "req"."altitude" AS "req_altitude",
    "req"."accuracy" AS "req_accuracy", "req"."timestamp" AS "req_timestamp",
    "req"."bearing" AS "req_bearing", "req"."speed" AS "req_speed",
    "last"."latitude" AS "last_latitude", "last"."longitude" AS "last_longitude",
    "last"."altitude" AS "last_altitude", "last"."accuracy" AS "last_accuracy",
    "last"."timestamp" AS "last_timestamp", "last"."bearing" AS "last_bearing",
    "last"."speed" AS "last_speed" FROM cells JOIN "positions" AS "req" ON
    (request_pos_id = "req"."_id") JOIN "positions" AS "last" ON (last_pos_id =
    "last"."_id") WHERE cells.session_id = ? ORDER BY request_pos_id LIMIT 3000
    OFFSET ?
    I/b       (11623): Database scheme version 10
    I/a       (11623): Cycle 0
    I/a       (11623): Serialize cells took 112 ms
    I/k       (11623): Exporting wifis
    D/m       (11623): Start wifi export. Data source:  SELECT wifis._id AS
    "_id",bssid, ssid, md5ssid, capabilities, frequency, level, wifis.timestamp,
    request_pos_id AS "request_pos_id",last_pos_id AS
    "last_pos_id",wifis.session_id, is_known AS "known_wifi", "req"."latitude" AS
    "req_latitude", "req"."longitude" AS "req_longitude", "req"."altitude" AS
    "req_altitude", "req"."accuracy" AS "req_accuracy", "req"."timestamp" AS
    "req_timestamp", "req"."bearing" AS "req_bearing", "req"."speed" AS "req_speed",
    "last"."latitude" AS "last_latitude", "last"."longitude" AS "last_longitude",
    "last"."altitude" AS "last_altitude", "last"."accuracy" AS "last_accuracy",
    "last"."timestamp" AS "last_timestamp", "last"."bearing" AS "last_bearing",
    "last"."speed" AS "last_speed" FROM wifis JOIN "positions" AS "req" ON
    ("request_pos_id" = "req"."_id") JOIN "positions" AS "last" ON ("last_pos_id" =
    "last"."_id") WHERE wifis.session_id = ? ORDER BY request_pos_id LIMIT 3000
    OFFSET ?
    I/d       (11623): Uploading
    /storage/emulated/0/Android/data/org.openbmap/filesV2_457_log20150804163856-cellular.xml
    I/b       (11623): Database scheme version 10
    I/m       (11623): Cycle 0
    I/m       (11623): Cycle 1000
    I/m       (11623): Serialize wifi took 549 ms
    I/d       (11623): Uploading
    /storage/emulated/0/Android/data/org.openbmap/filesV1_log20150804163842-wifi.xml
    I/k       (11623): Waiting for uploads to complete. (Active 3)
    I/d       (11623): Uploading
    /storage/emulated/0/Android/data/org.openbmap/filesV1_log20150804204213-wifi.xml
    I/k       (11623): Waiting for uploads to complete. (Active 3)
    I/k       (11623): Waiting for uploads to complete. (Active 3)
    I/k       (11623): Waiting for uploads to complete. (Active 3)
    I/k       (11623): Waiting for uploads to complete. (Active 3)
    I/k       (11623): Waiting for uploads to complete. (Active 3)
    I/SBar.MotoNetworkCtrlr( 2333): onReceive: WifiManager.RSSI_CHANGED_ACTION
    Received
    I/k       (11623): Waiting for uploads to complete. (Active 3)
    I/k       (11623): Waiting for uploads to complete. (Active 3)
    I/k       (11623): Waiting for uploads to complete. (Active 3)
    I/k       (11623): Waiting for uploads to complete. (Active 3)
    I/k       (11623): Waiting for uploads to complete. (Active 3)
    I/k       (11623): Waiting for uploads to complete. (Active 3)
    I/k       (11623): Waiting for uploads to complete. (Active 3)
    I/k       (11623): Waiting for uploads to complete. (Active 3)
    I/k       (11623): Waiting for uploads to complete. (Active 3)
    I/k       (11623): Waiting for uploads to complete. (Active 3)
    I/k       (11623): Waiting for uploads to complete. (Active 3)
    I/k       (11623): Waiting for uploads to complete. (Active 3)
    I/k       (11623): Waiting for uploads to complete. (Active 3)
    I/k       (11623): Waiting for uploads to complete. (Active 3)
    I/k       (11623): Waiting for uploads to complete. (Active 3)
    I/k       (11623): Waiting for uploads to complete. (Active 3)
    I/k       (11623): Waiting for uploads to complete. (Active 3)
    I/k       (11623): Waiting for uploads to complete. (Active 3)
    I/k       (11623): Waiting for uploads to complete. (Active 3)
    I/k       (11623): Waiting for uploads to complete. (Active 3)
    I/k       (11623): Waiting for uploads to complete. (Active 3)
    I/k       (11623): Waiting for uploads to complete. (Active 3)
    I/d       (11623): Uploaded
    /storage/emulated/0/Android/data/org.openbmap/filesV2_457_log20150804163856-cellular.xml:
    Server reply 200
    I/k       (11623): Finished upload, pending uploads 2
    I/k       (11623): Waiting for uploads to complete. (Active 2)
    I/k       (11623): Waiting for uploads to complete. (Active 2)
    I/k       (11623): Waiting for uploads to complete. (Active 2)
    I/k       (11623): Waiting for uploads to complete. (Active 2)
    I/k       (11623): Waiting for uploads to complete. (Active 2)
    I/k       (11623): Waiting for uploads to complete. (Active 2)
    I/k       (11623): Waiting for uploads to complete. (Active 2)
    I/k       (11623): Waiting for uploads to complete. (Active 2)
    I/k       (11623): Waiting for uploads to complete. (Active 2)
    I/k       (11623): Waiting for uploads to complete. (Active 2)
    I/k       (11623): Waiting for uploads to complete. (Active 2)
    I/k       (11623): Waiting for uploads to complete. (Active 2)
    I/k       (11623): Waiting for uploads to complete. (Active 2)
    I/k       (11623): Waiting for uploads to complete. (Active 2)
    I/k       (11623): Waiting for uploads to complete. (Active 2)
    I/k       (11623): Waiting for uploads to complete. (Active 2)
    I/k       (11623): Waiting for uploads to complete. (Active 2)
    I/k       (11623): Waiting for uploads to complete. (Active 2)
    I/k       (11623): Waiting for uploads to complete. (Active 2)
    I/k       (11623): Waiting for uploads to complete. (Active 2)
    I/k       (11623): Waiting for uploads to complete. (Active 2)
    I/k       (11623): Waiting for uploads to complete. (Active 2)
    I/k       (11623): Waiting for uploads to complete. (Active 2)
    I/k       (11623): Waiting for uploads to complete. (Active 2)
    I/k       (11623): Waiting for uploads to complete. (Active 2)
    I/k       (11623): Waiting for uploads to complete. (Active 2)
    I/k       (11623): Waiting for uploads to complete. (Active 2)
    I/k       (11623): Waiting for uploads to complete. (Active 2)
    I/k       (11623): Waiting for uploads to complete. (Active 2)
    I/k       (11623): Waiting for uploads to complete. (Active 2)
    I/k       (11623): Waiting for uploads to complete. (Active 2)
    I/k       (11623): Waiting for uploads to complete. (Active 2)
    I/k       (11623): Waiting for uploads to complete. (Active 2)
    I/k       (11623): Waiting for uploads to complete. (Active 2)
    I/k       (11623): Waiting for uploads to complete. (Active 2)
    I/k       (11623): Waiting for uploads to complete. (Active 2)
    I/d       (11623): Uploaded
    /storage/emulated/0/Android/data/org.openbmap/filesV1_log20150804204213-wifi.xml:
    Server reply 200
    I/k       (11623): Finished upload, pending uploads 1
    I/k       (11623): Waiting for uploads to complete. (Active 1)
    I/SBar.MotoNetworkCtrlr( 2333): onReceive: WifiManager.RSSI_CHANGED_ACTION
    Received
    I/k       (11623): Waiting for uploads to complete. (Active 1)
    I/k       (11623): Waiting for uploads to complete. (Active 1)
    I/k       (11623): Waiting for uploads to complete. (Active 1)
    I/k       (11623): Waiting for uploads to complete. (Active 1)
    I/k       (11623): Waiting for uploads to complete. (Active 1)
    I/k       (11623): Waiting for uploads to complete. (Active 1)
    I/k       (11623): Waiting for uploads to complete. (Active 1)
    I/k       (11623): Waiting for uploads to complete. (Active 1)
    I/k       (11623): Waiting for uploads to complete. (Active 1)
    I/k       (11623): Waiting for uploads to complete. (Active 1)
    I/k       (11623): Waiting for uploads to complete. (Active 1)
    I/k       (11623): Waiting for uploads to complete. (Active 1)
    I/k       (11623): Waiting for uploads to complete. (Active 1)
    I/k       (11623): Waiting for uploads to complete. (Active 1)
    I/k       (11623): Waiting for uploads to complete. (Active 1)
    I/k       (11623): Waiting for uploads to complete. (Active 1)
    I/k       (11623): Waiting for uploads to complete. (Active 1)
    I/k       (11623): Waiting for uploads to complete. (Active 1)
    I/k       (11623): Waiting for uploads to complete. (Active 1)
    I/k       (11623): Waiting for uploads to complete. (Active 1)
    I/k       (11623): Waiting for uploads to complete. (Active 1)
    I/k       (11623): Waiting for uploads to complete. (Active 1)
    I/k       (11623): Waiting for uploads to complete. (Active 1)
    I/k       (11623): Waiting for uploads to complete. (Active 1)
    I/k       (11623): Waiting for uploads to complete. (Active 1)
    I/k       (11623): Waiting for uploads to complete. (Active 1)
    I/k       (11623): Waiting for uploads to complete. (Active 1)
    I/k       (11623): Waiting for uploads to complete. (Active 1)
    I/k       (11623): Waiting for uploads to complete. (Active 1)
    I/k       (11623): Waiting for uploads to complete. (Active 1)
    I/k       (11623): Waiting for uploads to complete. (Active 1)
    I/k       (11623): Waiting for uploads to complete. (Active 1)
    I/d       (11623): Uploaded
    /storage/emulated/0/Android/data/org.openbmap/filesV1_log20150804163842-wifi.xml:
    Server reply 200
    I/k       (11623): Finished upload, pending uploads 0
    I/k       (11623): All files uploaded
    I/k       (11623): Deleting files skipped
    I/art     (11623): Explicit concurrent mark sweep GC freed 98653(4MB) AllocSpace
    objects, 2(120KB) LOS objects, 40% free, 8MB/14MB, paused 662us total 61.804ms
    I/k       (11623): Re-indexing SD card temp folder
    D/a       (11623): Updating existing session 11
    I/StartscreenActivity(11623): Session 11 exported
    I/StartscreenActivity(11623): Exported 1/1 sessions
    I/StartscreenActivity(11623): Export finished

**Comment by wish7code** [comment]
No worries, the cell files arrive fine, it's just an display problem!

While the server is able to process wifis on-the-fly, the cell processing is currently in manual operation mode (aka I've to press the button). So this explains why the cells didn't show up on the map till now. I just triggered such an update, so the cells should appear till tomorrow latest. 

I'm also working on enabling the automatic cell processing again.

PS: Could you have a look at the cell provider list at http://radiocells.org/country/la ?
I updated the cell provider names today by searching the internet and wikipedia for the actual cell provider names, but there's not much to be found online.. Did I catch all cell providers and are the names correct?

**Comment by wish7code** [comment]
Have a look at the results:
https://radiocells.org/country/LA

Feel free to re-open, if you still find any issues!

Cheers & thanks for reporting
Toby

**Comment by mbethke** [comment]
I see, thanks for clearing it up!
The cellphone provider list looks good and I think it's fairly complete although I'm no expert, I've only been here a couple of months.
