### ISSUE TITLE
Cell information not uploading?

### ISSUE THREAD

**Issue by takiainen** [wish7code/openbmap#89]
After uploading few thousand wifi networks and cell tower networks, it seems that only WIFIs show up at the online map http://radiocells.org/default/country/FI

My provider "Saunalahti" is also missing from the list at the page above. It might be due to the fact that it uses the same network as "Elisa" (which is listed), but the cells by Saunalahti nevertheless are not shown on the map. Clicking "Elisa" also claim that zero LTE networks are shown, despite I have uploaded several of them.

**Comment by wish7code** [comment]
Thanks for reporting! 

I just triggered a database rebuild, so everything should be fine by now.
(see http://radiocells.org/cell_provider/200)

Background: the cell update process is still a bit cumbersome: as the server dies from time to time while doing the automatic cell processing, I currently run the cell update manually. Thus it can take a couple of days, till new cells appear. Wifi updates in contrary run smoothly, so they appear automatically after a short time.

Cheers
Toby

PS: I also updated cell provider names. Could you verify, everything is fine there now?

**Comment by takiainen** [comment]
Wow, the map works like a charm now, and everything seems up to date! Good job.

**Comment by wish7code** [comment]
Glad to hear! If you still find any issues, feel free to reopen..

Cheers
Toby

**Comment by takiainen** [comment]
Hi again. It seems that the online map's cell tower information is lagging behind several weeks (at least in Finland).  And the online map in generally is really cumbersome: when zooming in, cell information disappears completely. Sometimes you can't see wifi information either. The yellow color for wifi is quite difficult to see also.

**Comment by wish7code** [comment]
Hello takiainen,

hope this is a display problem only: we triggered a map update so September towers should appear by now. Wifis should always be up-to-date (i.e. Oct. 7), cell towers might indeed lag a week, as we're still in manual import/processing mode (aka hit-the-button) for cells import.

> And the online map in generally is really cumbersome: when zooming in, cell information disappears completely. At some zoom levels you can't see wifi information either (it seems random, sometimes working, sometimes not). 

Zoom level 1-9 are cached, while higher zoom levels are generated on the fly. Hit F5 and wait, so the on-the-fly tiles should hopefully appear..

> The yellow color for wifi is quite difficult to see also 
Accepted, good point! Will experiment with a darker color (although very busy at the moment....)

Thanks & cheers 
Toby
