### ISSUE TITLE
A setting option about remove session after upload.

### ISSUE THREAD

**Issue by sim6** [wish7code/openbmap#96]
I want remove all the sessions after upload them. So, please could you add a setting option to store the action about remove session after upload?

**Comment by wish7code** [comment]
Hey Simo,

Have a look at e16c365d9cd5948d9037744b4515b8c6063fbc0f

Find the new option under Settings --> Advanced Settings --> Delete tracks

**Comment by sim6** [comment]
Thank you very much, I can enable the new option, but it doesn't work for me. :( The dialog is always displayed.

**Comment by wish7code** [comment]
Sorry Simó!!!! Guess I missed one code path..
Fixed in next release..

**Comment by sim6** [comment]
Now it works, thank you very much!
