### ISSUE TITLE
How can I contact you?

### ISSUE THREAD

**Issue by agilob** [wish7code/openbmap#98]
contact on openbmap tells to go to radiocells, where I can't find any contact details or form.

**Comment by wish7code** [comment]
Hey agilob!

team@radiocells.org is the way to go!

Looking forward to hearing from you,
Cheers 
Toby

**Comment by agilob** [comment]
Sent an email a few hours ago!

**Comment by wish7code** [comment]
Message well received.. Sounds like a really great idea!
I'm currently on a business trip, but let's continue our conversation next weekend when I'm back home..

Cheers 
Toby

**Comment by agilob** [comment]
Sure, it can wait. Please keep the conversation private ;)
